from __future__ import annotations

from pathlib import Path
from typing import Any

from weasyprint import HTML
from docx import Document
from docx.shared import Pt


_CSS = """
  @page { size: A4; margin: 22mm 18mm; }
  body { font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif; color: #1F2937; font-size: 11pt; }
  h1 { font-size: 18pt; margin-bottom: 0; color: #0E6AAD; }
  h2 { font-size: 12pt; margin-top: 16px; color: #0E6AAD; border-bottom: 1px solid #E5E7EB; padding-bottom: 4px; }
  p  { white-space: pre-wrap; line-height: 1.5; }
  .edited { color: #1F9D8F; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.04em; }
  .meta { color: #6B7280; font-size: 9pt; margin-bottom: 18px; }
"""


def render_report_pdf(data: dict, out_path: Path) -> None:
    sections = data.get("sections", [])
    html_parts = [
        "<html><head><meta charset='utf-8'><style>", _CSS,
        "</style></head><body>",
        "<h1>Echocardiography Report</h1>",
        "<div class='meta'>Generated by EchoChat Demo</div>",
    ]
    for sec in sections:
        html_parts.append(f"<h2>{sec['name']}"
                          f"{' <span class=edited>(edited)</span>' if sec.get('edited') else ''}</h2>")
        content = (sec.get("content") or "").strip() or "Not reported."
        html_parts.append(f"<p>{_escape(content)}</p>")
    html_parts.append("</body></html>")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    HTML(string="".join(html_parts)).write_pdf(str(out_path))


def render_report_docx(data: dict, out_path: Path) -> None:
    doc = Document()
    title = doc.add_heading("Echocardiography Report", level=1)
    meta = doc.add_paragraph("Generated by EchoChat Demo")
    for run in meta.runs:
        run.font.size = Pt(9)
    for sec in data.get("sections", []):
        h = doc.add_heading(sec["name"], level=2)
        if sec.get("edited"):
            r = doc.add_paragraph()
            er = r.add_run("(edited)")
            er.italic = True
            er.font.size = Pt(9)
        doc.add_paragraph((sec.get("content") or "").strip() or "Not reported.")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))


def _escape(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;"))
